# Generated by Django 6.0.3 on 2026-03-29 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_atual', models.FloatField()),
                ('nivel_critico', models.FloatField()),
                ('unidade_medida', models.CharField(choices=[('kg', 'Quilograma'), ('un', 'Unidade'), ('lt', 'Litro')], max_length=2)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_usada', models.FloatField(help_text='Quantidade para uma pizza média')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.insumo')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pizza')),
            ],
        ),
    ]
