# Generated by Django 6.0.3 on 2026-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='receitapizza',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Receita de Pizza', 'verbose_name_plural': 'Receitas de Pizzas'},
        ),
        migrations.AddField(
            model_name='insumo',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receitapizza',
            name='quantidade_usada',
            field=models.FloatField(help_text='Quantidade necessária para uma pizza média'),
        ),
    ]
