# Generated by Django 5.1.6 on 2026-04-27 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_fornecedor_options_alter_insumo_options_and_more'),
        ('vendas', '0002_ingrediente_remove_pizza_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receitapizza',
            options={},
        ),
        migrations.AlterField(
            model_name='insumo',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fornecedor'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nivel_critico',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='quantidade_atual',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='receitapizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita', to='vendas.pizza'),
        ),
        migrations.AlterField(
            model_name='receitapizza',
            name='quantidade_usada',
            field=models.FloatField(help_text='Qtd para uma pizza média'),
        ),
        migrations.CreateModel(
            name='AlertaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alerta', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('mensagem', models.TextField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.insumo')),
            ],
        ),
    ]
