# Generated by Django 6.0.3 on 2026-03-29 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome_avulso', models.CharField(help_text='Para pedidos por telefone sem cadastro', max_length=100)),
                ('horario_pedido', models.DateTimeField(auto_now_add=True)),
                ('horario_retirada_agendada', models.DateTimeField()),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('preparo', 'Em preparo'), ('forno', 'No forno'), ('pronto', 'Pronto para retirada')], default='recebido', max_length=20)),
                ('metodo_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro na Retirada'), ('online', 'Pagamento Online')], default='online', max_length=20)),
                ('prioridade', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.cliente')),
                ('pizzas', models.ManyToManyField(to='vendas.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Fornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_forno', models.DateTimeField(auto_now_add=True)),
                ('capacidade_maxima', models.IntegerField(default=9)),
                ('concluida', models.BooleanField(default=False)),
                ('pedidos', models.ManyToManyField(to='producao.pedido')),
            ],
        ),
    ]
