# Generated by Django 6.0.3 on 2026-03-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_nome_avulso',
            field=models.CharField(blank=True, help_text='Para pedidos por telefone sem cadastro', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horario_pedido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hora da Compra'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horario_retirada_agendada',
            field=models.DateTimeField(verbose_name='Previsão de Entrega/Retirada'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro na Retirada'), ('cartao_entrega', 'Cartão na Entrega'), ('pix', 'PIX'), ('online', 'Pagamento Online')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prioridade',
            field=models.BooleanField(default=False, help_text='Marque para pedidos prioritários (ex: Telefone)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('preparo', 'Em preparo'), ('forno', 'No forno'), ('pronto', 'Pronto para retirada'), ('entrega', 'Saiu para entrega'), ('concluido', 'Entregue / Finalizado'), ('cancelado', 'Cancelado')], default='recebido', max_length=20),
        ),
    ]
