# Generated by Django 5.1.6 on 2026-04-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_pedido_ultima_atualizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornada',
            name='capacidade_maxima',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ultima_atualizacao',
        ),
        migrations.AddField(
            model_name='fornada',
            name='previsao_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origem',
            field=models.CharField(choices=[('online', 'Online'), ('telefone', 'Telefone')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fornada',
            name='pedidos',
            field=models.ManyToManyField(related_name='fornadas', to='producao.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_nome_avulso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horario_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horario_retirada_agendada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prioridade',
            field=models.BooleanField(default=False),
        ),
    ]
