# Generated by Django 5.1.6 on 2026-04-27 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_contratacao',
        ),
        migrations.AddField(
            model_name='escalatrabalho',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Ex: Substituição por falta de João'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='escalatrabalho',
            name='data',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='escalatrabalho',
            name='funcionarios',
            field=models.ManyToManyField(related_name='escalas', to='gestao.funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(choices=[('preparo', 'Preparo/Massa'), ('cozinha', 'Pizzaiolo'), ('gerencia', 'Gerente de Pedidos'), ('entrega', 'Entregador')], max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FeedbackCliente',
        ),
    ]
